
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:1 (project)"
    message: |
      The system is: Windows - 10.0.17763 - AMD64
...
